/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cali2;

/**
 *
 * @author QUINTON KHUWISEB
 */
public class cali2 extends javax.swing.JFrame {

    double NumEnter1;
    double NumEnter2;
    double Result;
    String op;
    public cali2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void EnterNumbers(String q){
          //jtxtResult.setText("");
     String Nums = jtxtResult.getText() + q;
     jtxtResult.setText(Nums); 
     }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        calName = new javax.swing.JLabel();
        jtxtResult = new javax.swing.JTextField();
        btnDigit8 = new java.awt.Button();
        btnDigit7 = new java.awt.Button();
        btnDigit9 = new java.awt.Button();
        btnBS = new java.awt.Button();
        btnCE = new java.awt.Button();
        btnC = new java.awt.Button();
        btnPlus = new java.awt.Button();
        btnDigit1 = new java.awt.Button();
        btnDigit2 = new java.awt.Button();
        btnDigit3 = new java.awt.Button();
        btnDigit4 = new java.awt.Button();
        btnDigit5 = new java.awt.Button();
        btnDigit6 = new java.awt.Button();
        btnMinus = new java.awt.Button();
        btnMultiply = new java.awt.Button();
        btnDigit0 = new java.awt.Button();
        jbtnDot = new java.awt.Button();
        btnEquel = new java.awt.Button();
        btnDivide = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        calName.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        calName.setForeground(new java.awt.Color(255, 255, 255));
        calName.setText("Dr. SMILE's version of Casio");

        jtxtResult.setBackground(new java.awt.Color(0, 102, 102));
        jtxtResult.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtxtResult.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtResult.setText("lets see how dumb you can be!!");
        jtxtResult.setToolTipText("");
        jtxtResult.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtxtResult.setName("hhh"); // NOI18N
        jtxtResult.setSelectionColor(new java.awt.Color(153, 0, 153));
        jtxtResult.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtResultFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtResultFocusLost(evt);
            }
        });

        btnDigit8.setBackground(new java.awt.Color(51, 51, 51));
        btnDigit8.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnDigit8.setForeground(new java.awt.Color(255, 255, 255));
        btnDigit8.setLabel("8");
        btnDigit8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigit8ActionPerformed(evt);
            }
        });

        btnDigit7.setBackground(new java.awt.Color(51, 51, 51));
        btnDigit7.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnDigit7.setForeground(new java.awt.Color(255, 255, 255));
        btnDigit7.setLabel("7");
        btnDigit7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigit7ActionPerformed(evt);
            }
        });

        btnDigit9.setBackground(new java.awt.Color(51, 51, 51));
        btnDigit9.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnDigit9.setForeground(new java.awt.Color(255, 255, 255));
        btnDigit9.setLabel("9");
        btnDigit9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigit9ActionPerformed(evt);
            }
        });

        btnBS.setBackground(new java.awt.Color(51, 51, 51));
        btnBS.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btnBS.setForeground(new java.awt.Color(255, 255, 255));
        btnBS.setLabel("⇐");
        btnBS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBSActionPerformed(evt);
            }
        });

        btnCE.setBackground(new java.awt.Color(51, 51, 51));
        btnCE.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnCE.setForeground(new java.awt.Color(255, 255, 255));
        btnCE.setLabel("CE");
        btnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCEActionPerformed(evt);
            }
        });

        btnC.setBackground(new java.awt.Color(51, 51, 51));
        btnC.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnC.setForeground(new java.awt.Color(255, 255, 255));
        btnC.setLabel("C");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });

        btnPlus.setBackground(new java.awt.Color(51, 51, 51));
        btnPlus.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btnPlus.setForeground(new java.awt.Color(255, 255, 255));
        btnPlus.setLabel("+");
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });

        btnDigit1.setBackground(new java.awt.Color(51, 51, 51));
        btnDigit1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnDigit1.setForeground(new java.awt.Color(255, 255, 255));
        btnDigit1.setLabel("1");
        btnDigit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigit1ActionPerformed(evt);
            }
        });

        btnDigit2.setBackground(new java.awt.Color(51, 51, 51));
        btnDigit2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnDigit2.setForeground(new java.awt.Color(255, 255, 255));
        btnDigit2.setLabel("2");
        btnDigit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigit2ActionPerformed(evt);
            }
        });

        btnDigit3.setBackground(new java.awt.Color(51, 51, 51));
        btnDigit3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnDigit3.setForeground(new java.awt.Color(255, 255, 255));
        btnDigit3.setLabel("3");
        btnDigit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigit3ActionPerformed(evt);
            }
        });

        btnDigit4.setBackground(new java.awt.Color(51, 51, 51));
        btnDigit4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnDigit4.setForeground(new java.awt.Color(255, 255, 255));
        btnDigit4.setLabel("4");
        btnDigit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigit4ActionPerformed(evt);
            }
        });

        btnDigit5.setBackground(new java.awt.Color(51, 51, 51));
        btnDigit5.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnDigit5.setForeground(new java.awt.Color(255, 255, 255));
        btnDigit5.setLabel("5");
        btnDigit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigit5ActionPerformed(evt);
            }
        });

        btnDigit6.setBackground(new java.awt.Color(51, 51, 51));
        btnDigit6.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnDigit6.setForeground(new java.awt.Color(255, 255, 255));
        btnDigit6.setLabel("6");
        btnDigit6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigit6ActionPerformed(evt);
            }
        });

        btnMinus.setBackground(new java.awt.Color(51, 51, 51));
        btnMinus.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btnMinus.setForeground(new java.awt.Color(255, 255, 255));
        btnMinus.setLabel("-");
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });

        btnMultiply.setBackground(new java.awt.Color(51, 51, 51));
        btnMultiply.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btnMultiply.setForeground(new java.awt.Color(255, 255, 255));
        btnMultiply.setLabel("*");
        btnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplyActionPerformed(evt);
            }
        });

        btnDigit0.setBackground(new java.awt.Color(51, 51, 51));
        btnDigit0.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnDigit0.setForeground(new java.awt.Color(255, 255, 255));
        btnDigit0.setLabel("0");
        btnDigit0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigit0ActionPerformed(evt);
            }
        });

        jbtnDot.setBackground(new java.awt.Color(51, 51, 51));
        jbtnDot.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jbtnDot.setForeground(new java.awt.Color(255, 255, 255));
        jbtnDot.setLabel(".");
        jbtnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDotActionPerformed(evt);
            }
        });

        btnEquel.setBackground(new java.awt.Color(51, 51, 51));
        btnEquel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btnEquel.setForeground(new java.awt.Color(255, 255, 255));
        btnEquel.setLabel("=");
        btnEquel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquelActionPerformed(evt);
            }
        });

        btnDivide.setBackground(new java.awt.Color(51, 51, 51));
        btnDivide.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btnDivide.setForeground(new java.awt.Color(255, 255, 255));
        btnDivide.setLabel("÷");
        btnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivideActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBS, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDigit7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnDigit8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnDigit9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDigit4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnDigit5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnDigit6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDigit1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnDigit2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnDigit3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDigit0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jbtnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEquel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 9, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(calName, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(calName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jtxtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBS, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDigit7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDigit8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDigit9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDigit4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDigit5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDigit6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDigit1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDigit2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDigit3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDigit0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEquel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jtxtResult.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDigit8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigit8ActionPerformed
        EnterNumbers("8");
    }//GEN-LAST:event_btnDigit8ActionPerformed

    private void btnDigit7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigit7ActionPerformed
        EnterNumbers("7");
    }//GEN-LAST:event_btnDigit7ActionPerformed

    private void btnDigit9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigit9ActionPerformed
        EnterNumbers("9");
    }//GEN-LAST:event_btnDigit9ActionPerformed

    private void btnBSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBSActionPerformed

        String backsp = null;

        if (jtxtResult.getText().length() > 0) {

            StringBuilder sb = new StringBuilder(jtxtResult.getText());
            sb.deleteCharAt(jtxtResult.getText().length() - 1);
            backsp = sb.toString();
            jtxtResult.setText(backsp);
        }
    }//GEN-LAST:event_btnBSActionPerformed

    private void btnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCEActionPerformed
        jtxtResult.setText("");

        String Fn, Sn;

        Fn = String.valueOf(NumEnter1);
        Sn = String.valueOf(NumEnter2);

        Fn = "";
        Sn = "";
    }//GEN-LAST:event_btnCEActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        jtxtResult.setText("");
    }//GEN-LAST:event_btnCActionPerformed

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
                      //  EnterNumbers("+");


        NumEnter1 = Double.parseDouble(jtxtResult.getText());
        jtxtResult.setText("+");
        op ="+";
    }//GEN-LAST:event_btnPlusActionPerformed

    private void btnDigit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigit1ActionPerformed
        EnterNumbers("1");
    }//GEN-LAST:event_btnDigit1ActionPerformed

    private void btnDigit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigit2ActionPerformed
        EnterNumbers("2");
    }//GEN-LAST:event_btnDigit2ActionPerformed

    private void btnDigit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigit3ActionPerformed
        EnterNumbers("3");
    }//GEN-LAST:event_btnDigit3ActionPerformed

    private void btnDigit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigit4ActionPerformed
        EnterNumbers("4");
    }//GEN-LAST:event_btnDigit4ActionPerformed

    private void btnDigit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigit5ActionPerformed
        EnterNumbers("5");
    }//GEN-LAST:event_btnDigit5ActionPerformed

    private void btnDigit6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigit6ActionPerformed
        EnterNumbers("6");
    }//GEN-LAST:event_btnDigit6ActionPerformed

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        NumEnter1 = Double.parseDouble(jtxtResult.getText());
        //jtxtResult.setText("");
        op ="-";
    }//GEN-LAST:event_btnMinusActionPerformed

    private void btnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplyActionPerformed
        NumEnter1 = Double.parseDouble(jtxtResult.getText());
       // 
        op ="*";
        jtxtResult.setText("");
    }//GEN-LAST:event_btnMultiplyActionPerformed

    private void btnDigit0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigit0ActionPerformed
        EnterNumbers("0");
    }//GEN-LAST:event_btnDigit0ActionPerformed

    private void jbtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDotActionPerformed
        if (! jtxtResult.getText().contains(".")){
           // jtxtResult.setText(jtxtResult.getText() + jbtnDot.getText());
        }
    }//GEN-LAST:event_jbtnDotActionPerformed

    private void btnEquelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquelActionPerformed
        NumEnter2 = Double.parseDouble(jtxtResult.getText());
        if (op == "+"){
            Result = NumEnter1 + NumEnter2;
            jtxtResult.setText(String.valueOf(Result));
        }
        else if (op == "-"){
            Result = NumEnter1 - NumEnter2;
            jtxtResult.setText(String.valueOf(Result));
        }
        else if (op == "*"){
            Result = NumEnter1 * NumEnter2;
            jtxtResult.setText(String.valueOf(Result));
        }
        else if (op == "/"){
            Result = NumEnter1 / NumEnter2;
            jtxtResult.setText(String.valueOf(Result));
        }
    }//GEN-LAST:event_btnEquelActionPerformed

    private void btnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivideActionPerformed
        NumEnter1 = Double.parseDouble(jtxtResult.getText());
        //jtxtResult.setText("");
        op ="/";
    }//GEN-LAST:event_btnDivideActionPerformed

    private void jtxtResultFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtResultFocusGained
        if (jtxtResult.getText().equals("lets see how dumb you can be!!")) {
        jtxtResult.setText("");
    }//GEN-LAST:event_jtxtResultFocusGained
    }
    private void jtxtResultFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtResultFocusLost
        if (jtxtResult.getText().isEmpty()) {
        jtxtResult.setText("");
        }
    }//GEN-LAST:event_jtxtResultFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cali2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cali2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cali2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cali2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cali2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnBS;
    private java.awt.Button btnC;
    private java.awt.Button btnCE;
    private java.awt.Button btnDigit0;
    private java.awt.Button btnDigit1;
    private java.awt.Button btnDigit2;
    private java.awt.Button btnDigit3;
    private java.awt.Button btnDigit4;
    private java.awt.Button btnDigit5;
    private java.awt.Button btnDigit6;
    private java.awt.Button btnDigit7;
    private java.awt.Button btnDigit8;
    private java.awt.Button btnDigit9;
    private java.awt.Button btnDivide;
    private java.awt.Button btnEquel;
    private java.awt.Button btnMinus;
    private java.awt.Button btnMultiply;
    private java.awt.Button btnPlus;
    private javax.swing.JLabel calName;
    private javax.swing.JPanel jPanel1;
    private java.awt.Button jbtnDot;
    private javax.swing.JTextField jtxtResult;
    // End of variables declaration//GEN-END:variables
}
