package phonebooksystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class viewContacts extends javax.swing.JFrame {

    /**
     * Creates new form addContact
     */
    public viewContacts() {
        initComponents();
        
         // DB Connection & Login Check
    
        String url = "jdbc:mysql://localhost:3306/Phonebooksystem";
        String dbUser = "root";         // change if different
        String dbPassword = "1234";         // your MySQL password

        

        try{ 
            Connection conn = DriverManager.getConnection(url, dbUser, dbPassword);
             PreparedStatement st = conn.prepareStatement("select * from Contacts ORDER BY FirstName ASC;");
                
            

            ResultSet rs;
            rs = st.executeQuery();
            
            
            //this gets the values from the columns in the "" from the database
            while(rs.next()){
            String name = rs.getString("FirstName");
            String genre = rs.getString("LastName");
            String season = rs.getString("FirstNumber");
            String status = rs.getString("SecondNumber");
            
            //this sets those values into an array called tabledata and uses that array to add to the actual table
            String tableData[] = {name, genre, season, status};
            DefaultTableModel tbml = (DefaultTableModel)jTable1.getModel();
            tbml.addRow(tableData);
         
            
                }
            

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
            return ;
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jMenuItem2 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        viewContact = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        SearchContactBtn = new javax.swing.JButton();
        contactSearchField = new javax.swing.JTextField();
        back1 = new javax.swing.JButton();
        Category = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("View Contacts");

        viewContact.setBackground(new java.awt.Color(0, 204, 204));
        viewContact.setFont(new java.awt.Font("Calibri", 0, 70)); // NOI18N
        viewContact.setForeground(new java.awt.Color(255, 204, 102));
        viewContact.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewContact.setText("View Contacts");
        viewContact.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Last Name", "First Number", "Second Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setFocusCycleRoot(true);
        jTable1.setFocusTraversalPolicyProvider(true);
        jTable1.setInheritsPopupMenu(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        SearchContactBtn.setBackground(new java.awt.Color(0, 102, 102));
        SearchContactBtn.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        SearchContactBtn.setForeground(new java.awt.Color(255, 204, 102));
        SearchContactBtn.setText("Search");
        SearchContactBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchContactBtnMouseClicked(evt);
            }
        });
        SearchContactBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchContactBtnActionPerformed(evt);
            }
        });

        back1.setBackground(new java.awt.Color(0, 102, 102));
        back1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        back1.setForeground(new java.awt.Color(255, 204, 102));
        back1.setText("Back");
        back1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back1MouseClicked(evt);
            }
        });

        Category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Friends", "Family", "School ", "Baha'i" }));
        Category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoryActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 102));
        jLabel1.setText("Category:");

        jDesktopPane1.setLayer(viewContact, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(SearchContactBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(contactSearchField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(back1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Category, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(back1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Category, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewContact))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(contactSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SearchContactBtn)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewContact)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchContactBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(back1)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchContactBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchContactBtnMouseClicked
         String url = "jdbc:mysql://localhost:3306/Phonebooksystem";
        String dbUser = "root";         // change if different
        String dbPassword = "1234";         // your MySQL password

        String keyword = contactSearchField.getText();

        try{ 
            Connection conn = DriverManager.getConnection(url, dbUser, dbPassword);
             PreparedStatement st = conn.prepareStatement("select * from Contacts where FirstName LIKE ? OR FirstNumber LIKE ? OR SecondNumber LIKE ?");
                
             st.setString(1, "%" + keyword + "%");
             st.setString(2, "%" + keyword + "%");
             st.setString(3, "%" + keyword + "%");
            
            ResultSet rs;
            rs = st.executeQuery();
            
            
           
            
            while(rs.next()){
                
            String name = rs.getString("FirstName");
            String lastName = rs.getString("LastName");
            String firstnumber = rs.getString("FirstNumber");
            String secondnumber = rs.getString("SecondNumber");
            
            
            String tableData[] = {name, lastName, firstnumber, secondnumber};
            DefaultTableModel tbml = (DefaultTableModel)jTable1.getModel();
            tbml.setRowCount(0);
            tbml.addRow(tableData);
            }
              
            

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
            return ;
        }
    }//GEN-LAST:event_SearchContactBtnMouseClicked

    private void back1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back1MouseClicked
       setVisible(false);
        new mainMenu().setVisible(true);
    }//GEN-LAST:event_back1MouseClicked

    private void SearchContactBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchContactBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchContactBtnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void CategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoryActionPerformed
         String url = "jdbc:mysql://localhost:3306/Phonebooksystem";
        String dbUser = "root";         // change if different
        String dbPassword = "1234";         // your MySQL password
        
        String selectedCategory = (String)
                Category.getSelectedItem();
                

      //  boolean found = true;
        
        try{ 
                    Connection conn = DriverManager.getConnection(url, dbUser, dbPassword);

            String DBQuary;
            PreparedStatement st;
        if(selectedCategory.equals("All") ){
        DBQuary = "select * from Contacts ";
                      st = conn.prepareStatement(DBQuary);

        }
        else{
            DBQuary = "select * from Contacts where Category = ?";
                      st = conn.prepareStatement(DBQuary);
             st.setString(1, selectedCategory);

        }
     
            ResultSet rs;
            rs = st.executeQuery();
                        DefaultTableModel tbml = (DefaultTableModel)jTable1.getModel();
           tbml.setRowCount(0);

           /*if(!rs.next()){
           }
           else{*/
            
            while(rs.next()){
                
                
            String name = rs.getString("FirstName");
            String lastName = rs.getString("LastName");
            String firstnumber = rs.getString("FirstNumber");
            String secondnumber = rs.getString("SecondNumber");
            
            
            String tableData[] = {name, lastName, firstnumber, secondnumber};
            //DefaultTableModel tbml = (DefaultTableModel)jTable1.getModel();
            //tbml.setNumRows(0);
            tbml.addRow(tableData);
            
            
            } 
            

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
            return ;
        }
    }//GEN-LAST:event_CategoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addContact().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Category;
    private javax.swing.JButton SearchContactBtn;
    private javax.swing.JButton back1;
    private javax.swing.JTextField contactSearchField;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTable1;
    private javax.swing.JLabel viewContact;
    // End of variables declaration//GEN-END:variables
}
